### ISSUE TITLE
Error: Unable to call `appDocumentFooter`, which is undefined or falsey (via Template render error)

### ISSUE THREAD

**Issue by alex-hedley** [x-govuk/govuk-eleventy-plugin#114] opened 2023-01-12 10:52 UTC
Looking to upgrade to [[3.0.3]](https://github.com/x-govuk/govuk-eleventy-plugin/tree/v3.0.3) after seeing https://github.com/x-govuk/govuk-eleventy-plugin/issues/60 but having an issue. Think it might be my config, but unsure.

I'm using this with the [design-history-template](https://github.com/x-govuk/govuk-design-history-template), should I raise it there instead?

`package.json`
```json
    "govuk-eleventy-plugin": "^3.0.3",
```

I ran `npm run start`

```
> govuk-design-history@2.0.0 start
> eleventy --serve --quiet

[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing template: "public/example-post/index.html" (via EleventyTemplateError)
[11ty] 2. (./app/_layouts/post.njk) [Line 11, Column 26]
[11ty]   Error: Unable to call `appDocumentFooter`, which is undefined or falsey (via Template render error)
[11ty] 
[11ty] Original error stack trace: Template render error: (./app/_layouts/post.njk) [Line 11, Column 26]
[11ty]   Error: Unable to call `appDocumentFooter`, which is undefined or falsey
[11ty]     at Object._prettifyError (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/lib.js:36:11)
[11ty]     at /Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:563:19
[11ty]     at eval (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:148:12)
[11ty]     at eval (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:287:12)
[11ty]     at b_content (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:138:3)
[11ty]     at eval (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:286:28)
[11ty]     at b_beforeContent (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:42:1)
[11ty]     at b_main (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:273:34)
[11ty]     at eval (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:147:83)
[11ty]     at b_header (eval at _compile (/Users/alexhedley/govuk-design-history-template/node_modules/nunjucks/src/environment.js:633:18), <anonymous>:378:1)
[11ty] Wrote 0 files in 0.66 seconds (v1.0.2)
```

---

I was on an older version of node so I've upgraded to various versions to try it out.

| npm | node |
| - | - | 
| 8.19.3 | v14.18.2 |

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'govuk-design-history@2.0.0',
npm WARN EBADENGINE   required: { node: '^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.18.2', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'govuk-eleventy-plugin@3.0.3',
npm WARN EBADENGINE   required: { node: '^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.18.2', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'govuk-prototype-components@1.0.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.18.2', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'markdown-it-govuk@0.1.3',
npm WARN EBADENGINE   required: { node: '>=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.18.2', npm: '8.19.3' }
npm WARN EBADENGINE }
```

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

| npm | node |
| - | - | 
| 8.19.3 | v16.19.0 |

```
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
```

| npm | node |
| - | - | 
| 8.19.3 | v18.13.0 |

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'govuk-design-history@2.0.0',
npm WARN EBADENGINE   required: { node: '^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '8.19.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'govuk-eleventy-plugin@3.0.3',
npm WARN EBADENGINE   required: { node: '^16.0.0' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```

**Comment by paulrobertlloyd** [comment] 2023-01-12 16:40
Hmmm, I wonder if this issue is caused by #97 – will take a look.

**Comment by paulrobertlloyd** [comment] 2023-01-12 21:57
Found the issue; v3.0.3 contained a breaking change. If you want to fix your design history in the meantime, make the change shown in this PR: https://github.com/x-govuk/govuk-design-history-template/pull/203/files

**Comment by alex-hedley** [comment] 2023-01-13 08:56
Great, that worked, thanks.

**Comment by paulrobertlloyd** [comment] 2023-01-13 11:02
Version v3.0.3 has been deprecated due ti it containing this breaking change, and v4.0.0 has been released with the changes in that release.

**Closed by paulrobertlloyd** 2023-01-13 11:02 UTC
